### ISSUE TITLE
setf expansion doesn't work on ecl

### ISSUE THREAD

**Issue by charJe** [phoe/binding-arrows#3]
```
;;; Error:
;;;   in file test.lisp, position 10208
;;;   at (DEFTEST SETF--> ...)
;;;   * The macro form (SETF (-> 0 (NTHCDR LIST) CDR CDR CAR) 42) was not expanded successfully.
;;; Error detected:
;;; Wrong number of arguments passed to function #<compiled-function 0x7fc00f5e0040>.ASDF could not load binding-arrows/test because
COMPILE-FILE-ERROR while
compiling #<cl-source-file "binding-arrows/test" "test">.
```

Strangely, I find that replacing `&body` with `&rest` in the `define-arrow` forms makes the setf expanders work.

**Comment by phoe** [comment]
This makes no sense from the CL point of view - `&body` and `&rest` are meant to be interchangeable. Are you able to descend into the file and find a more minimal test case that we can then try to reproduce? What is your ECL version?

**Comment by charJe** [comment]
ecl version: 21.2.1

It is the frist setf test that fails. The `(-> 0 (NTHCDR LIST) CDR CDR CAR)` properly yields 3, but `(SETF (-> 0 (NTHCDR LIST) CDR CDR CAR) 42)` has trouble macroexpanding with this error:
```
Wrong number of arguments passed to function #<compiled-function 0x7ff519a2d5c0>.
   [Condition of type SI:SIMPLE-PROGRAM-ERROR]
```
I believe that compiled function is `nthcdr`. I'm not sure how to get a useful backtrace from ecl.

**Comment by phoe** [comment]
I don't think I will be able to help debugging this one - I'm not competent enough with ECL and I won't have the time to dig into the source code at the moment. Perhaps you could try to dig into it yourself, try to e.g. slime-macrostep `DEFINE-ARROW` to expand it into smaller components, and minimize the test case by trying to find the smallest `DEFINE-SETF-EXPANDER` that fails, at which point we could try to reason if the bug is in my code or if it's an ECL-specific issue.

Still, it's very strange that `&rest` works whereas `&body` doesn't, and unless something weird is going on, perhaps that alone could be worth investigating.

**Comment by charJe** [comment]
I have determined that this is indeed a bug with ECL. A known one at that: https://gitlab.com/embeddable-common-lisp/ecl/-/issues/627.

**Comment by phoe** [comment]
TIL! Thank you.
